import './globals.css'
import { Inter } from 'next/font/google'
import ClientLayout from './components/ClientLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main_container">
        {/* Use the ClientLayout here */}
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  )
}
